version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: learning-it
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: learning-it
      MYSQL_USER: 'duy'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3309:3306

  redis:
    image: 'redis:6-alpine'
    container_name: learnit-redis
    ports:
      - 6382:6379
